## Credit Risk Analysis Project
### 365 Data Science: Complete Data Analysis Bootcamp

In this project, I am preparing a loan application dataset in order for it to be used in a Machine Learning model to predict the probability of default.

In [1]:
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
np.set_printoptions(suppress= True, linewidth= 100, precision= 2)

In [3]:
path = 'loan-data.csv'
raw_data_np = np.genfromtxt(path, delimiter = ';', skip_header = 1, autostrip = True, encoding =  'latin1')
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

### Checking for Incomplete Data

#### First I will check the number of missing values

In [4]:
np.isnan(raw_data_np).sum()

88005

In [5]:
#I will now establish how I will temporarily fill the missing values
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis = 0)

In [6]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

#### Here, I can see that there are 8 columns that consist of text values. This is important as it will impact how I will split the data later on.

In [7]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
                            temporary_mean,
                            np.nanmax(raw_data_np, axis = 0)])

### Splitting the Data

#### I will first determine which columns contain string values and which ones contain numeric values

In [8]:
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_numeric = np.argwhere(np.isnan(temporary_mean)== False).squeeze()

In [9]:
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [10]:
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

### Re-Importing the Dataset

In [12]:
path = 'loan-data.csv'

loan_data_strings = np.genfromtxt(path, delimiter = ';',
                                  skip_header = 1,
                                  autostrip = True,
                                  encoding =  'latin1',
                                  usecols = columns_strings,
                                  dtype = str)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [13]:
loan_data_numeric = np.genfromtxt(path, delimiter = ';',
                                  skip_header = 1,
                                  autostrip = True,
                                  encoding =  'latin1',
                                  usecols = columns_numeric,
                                  filling_values = temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### Adding the Column Names to the 2 Datasets

#### First I will store all of the headers in a variable

In [14]:
header_full = np.genfromtxt(path, delimiter = ';',
                                  autostrip = True,
                                  encoding =  'latin1',
                                  skip_footer = raw_data_np.shape[0],
                                  dtype = str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [15]:
header_strings, header_numeric = header_full[columns_strings],header_full[columns_numeric]

In [16]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [17]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Manipulating String Columns

### Making Headers More Clear

In [18]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Since the first header might be a bit unclear, I will change it

In [19]:
header_strings[0] = 'issue_date'

In [20]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### 1. Issue Date

In [21]:
np.unique(loan_data_strings[:, 0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

#### Here I can see that all of the loan issue dates occurred in 2015. Therefore, I can remove the '-15' without losing any meaning from the data.

In [22]:
loan_data_strings[:, 0] = np.chararray.strip(loan_data_strings[:, 0], '-15')

In [23]:
loan_data_strings[:, 0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

#### In order to cut down on memory use, I will now change the month string to the corresponding integer.

In [24]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

#### I will use a for loop to iterate over the column and assign an integer for string values. "0" indicates missing data.

In [25]:
for i in range (13):
  loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                    i,
                                    loan_data_strings[:,0])

In [26]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### 2. Loan Status

In [27]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

#### In reviewing these candidates, the bank would like these statuses categorized into either "good" or "bad" financial condition. 1 will indicate "good", and 0 will indicate "bad".

In [28]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [29]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], status_bad), 0, 1)

In [30]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

### 3. Term

In [31]:
loan_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

#### Since the text 'months' does not provide meaningful value, I will strip it from the column. I will also rename the header to "term_months" so that the numeric values are clear.

In [32]:
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2], ' months')
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [33]:
header_strings[2] = 'term_months'

#### In credit risk modeling, one assumes the worst. Therefore, the missing values will receive the worst value of "60" months.

In [34]:
loan_data_strings[:, 2] = np.where(loan_data_strings[:, 2] == '',
                                   60,
                                   loan_data_strings[:, 2])

In [35]:
np.unique(loan_data_strings[:, 2])

array(['36', '60'], dtype='<U69')

### 4. Grade and Subgrade

In [36]:
np.unique(loan_data_strings[:, 3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [37]:
np.unique(loan_data_strings[:, 4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### When considering how to fill in the missing data in the "Subgrade" column, I will fill it in with the worst value in its own grade (for example: B will be B5) instead of the worst overall score - G5

In [38]:
for i in np.unique(loan_data_strings[:,3])[1:]:
  loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                    i + '5',
                                    loan_data_strings[:,4])

In [39]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Here, I can see that there are still some missing values in this column, where both the grade and the subgrade are missing. Because credit risk analysis is risk averse, there is a penalty for not disclosing this information. The appropriate step then is to create a new category following the convention. Those applicants who do not provide any of this information will be labeled as 'H1'

In [40]:
loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '',
                                  'H1',
                                  loan_data_strings[:,4])

In [41]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### At this point, the Grade column is no longer necessary, so I will drop it from the dataset.


In [42]:
loan_data_strings = np.delete(loan_data_strings, 3, axis = 1)

In [43]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [44]:
header_strings = np.delete(header_strings,3)

In [45]:
header_strings[3]

'sub_grade'

#### I will need to assign a numeric value along with the subgrade score, so I will create a dictionary.

In [46]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range (1, np.unique(loan_data_strings[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

#### Now I will apply the numeric score to each subgrade

In [47]:
for i in np.unique(loan_data_strings[:,3]):
  loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i,
                                    dict_sub_grade[i],
                                    loan_data_strings[:,3])

In [48]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### 5. Verification Status

In [49]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

#### This column indicates in the investor's funds are verified or not. Missing data is equivalent to "Not Verified", while "Source Verified" and "Verified" have the same meaning. In keeping with convention, 1 will denote the "good" category, and 0 will mean the "bad" category.

In [50]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'), 0, 1)

In [51]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

### 6. URL

In [52]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

#### Here, I can see that much of this information is repeated, so I will strip some of the data.

In [53]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

#### I suspect that these are the same numeric values as those in the "loan_ID" column, but I will make sure.

In [54]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [55]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [56]:
np.array_equal(loan_data_numeric[:,0].astype(dtype = np.int32), loan_data_strings[:,5].astype(dtype = np.int32))

True

#### Now that I know for certain that the info in the URL column is the same as the Loan ID, I can delete it.

In [57]:
loan_data_strings = np.delete(loan_data_strings, 5, axis = 1)
header_strings = np.delete(header_strings,5)

In [58]:
loan_data_strings[:, 5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [59]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

### 7. Address State 

In [60]:
header_strings[5]= 'state_address'

In [61]:
np.unique(loan_data_strings[:, 5], return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27]))

In [62]:
states_names, states_count = np.unique(loan_data_strings[:, 5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

#### After sorting the states by number of applicants, I can see that the category of "Missing Data" is in the 5th position with 500 applicants.

#### As we can see, a large portion of the applicants have addresses in the first four states. If I divided the data by state, outliers would have a strong influence particularly on states that are less represented. Instead, I will divide them by region.

#### First, I will label missing data in the column as "0", so it won't interfere with the analysis

In [63]:
loan_data_strings[:, 5] = np.where(loan_data_strings[:, 5] == '',
                                   0,
                                   loan_data_strings[:, 5])

In [64]:
states_west = np.array(['AZ', 'CO', 'MT', 'NM', 'NV', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA'])
states_south = np.array(['AL','DC', 'DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA', 'WV', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX'])
states_midwest = np.array(['IN', 'IL', 'MI', 'OH','WI', 'KS', 'MN', 'MO', 'ND', 'NE', 'SD'])
states_east = np.array(['CT', 'MA', 'ME', 'NH', 'RI', 'VT', 'NJ', 'NY', 'PA'])

In [65]:
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_west), 1,loan_data_strings[:, 5])
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_south), 2,loan_data_strings[:, 5])
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_midwest), 3,loan_data_strings[:, 5])
loan_data_strings[:, 5] = np.where(np.isin(loan_data_strings[:, 5], states_east), 4,loan_data_strings[:, 5])

In [66]:
np.unique(loan_data_strings[:, 5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

#### Now each reqion has a corresponding numeric value.

### Converting to Integers

In [67]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [69]:
loan_data_strings = loan_data_strings.astype(int)

In [70]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

## Manipulating Numeric Columns

In [71]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [72]:
np.isnan(loan_data_numeric).sum()

0

#### I can see that there are no longer any 'Nan' values.

### 8. ID

In [73]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [74]:
temporary_fill

68616520.0

#### I will first see if the filler value was used in the ID column

In [75]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum()

0

In [76]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### For all of these categories the "worst" value is the max, except for "funded-amt' where it is the minimum. This will help guide how I fill in the missing data.

### Temporary Stats

In [77]:
temporary_stats[:, columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

### 9. Funded Amount

In [78]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [79]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill,
temporary_stats[0, columns_numeric[2]],
loan_data_numeric[:,2])

loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### 10. Loaned Amount, Interest Rate, Total Payment, & Installment

#### Because credit analysis is risk averse, in these categories, the max value in the column will be used to fill in the missing values.

In [80]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [81]:
for i in [1,3,4,5]:
  loan_data_numeric[:, 1] = np.where(loan_data_numeric[:, i] == temporary_fill,
temporary_stats[2, columns_numeric[i]],
loan_data_numeric[:,i])

In [82]:
loan_data_numeric

array([[48010226.  ,     9452.96,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,     4679.7 ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,     1969.83,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,     2185.64,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  ,     3199.4 ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,      301.9 ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### 11. Currency Conversion

#### This data came from the US office to the main European bank. Therefore, the amounts that are in USD need to be converted to EUR.

In [83]:
#Dataset of Monthly Exchange Rates for 2015
EUR_USD = np.genfromtxt('EUR-USD.csv', delimiter= ',', autostrip = True, skip_header= 1, usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

#### Now, I will add a column for the monthly exchange rate

In [84]:
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [85]:
exchange_rate = loan_data_strings[:,0]

for i in range(1,13):
  exchange_rate = np.where(exchange_rate == i,
                           EUR_USD[i-1],
                           exchange_rate)

  exchange_rate = np.where(exchange_rate == 0,
                           np.mean(EUR_USD),
                           exchange_rate)
  exchange_rate

In [86]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [87]:
exchange_rate.shape

(10000,)

In [88]:
loan_data_numeric.shape

(10000, 6)

In [89]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [90]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [91]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### USD to EUR

In [92]:
columns_dollar = np.array([1,2,4,5])

In [93]:
loan_data_numeric[:, 6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

#### I will now use a for loop to divide all of the USD values in the specified columns by the exchange rate column in order to provide a EUR value.

In [94]:
for i in columns_dollar:
  loan_data_numeric = np.hstack((loan_data_numeric,
                                np.reshape(loan_data_numeric[:, i]/loan_data_numeric[:,6], (10000,1))))

In [95]:
loan_data_numeric.shape

(10000, 11)

#### Expanding the header

#### I will add more information in the headers to clearly indicate the currency of the column.

In [96]:
header_additional = np.array([column_name + "_EUR" for column_name in header_numeric[columns_dollar]])

In [97]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [98]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [99]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [100]:
header_numeric[columns_dollar] = np.array([column_name + "_USD" for column_name in header_numeric[columns_dollar]])

In [101]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [102]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [103]:
header_numeric = header_numeric[columns_index_order]

In [104]:
loan_data_numeric = loan_data_numeric[:, columns_index_order]

## Creating the Complete Dataset

In [105]:
loan_data_strings.shape

(10000, 6)

In [106]:
loan_data_numeric.shape

(10000, 11)

In [107]:
loan_data = np.hstack((loan_data_numeric, loan_data_strings))

In [108]:
np.isnan(loan_data).sum()

0

In [109]:
header_full = np.concatenate((header_numeric, header_strings))

#### Sorting the new dataset

In [110]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [111]:
loan_data = np.vstack((header_full, loan_data))

In [112]:
np.savetxt('preprocessed_loan_data.csv',
           loan_data, fmt = '%s')

#### Now, the dataset is ready for a model to predict probability of default. The text values have been changed to numeric values, monetary values from USD to EUR were calculated using daily exchange rate values, and principles of credit risk analysis guided decisions around categorizing applicants.